const input = {
  uid: "lkq2s1575t962k3t",
  gameSystemId: 4,
  name: "Dwarves v2.11",
  hint: "For Army Forge testing",
  background: "",
  armyWideRule: {},
  units: [
    {
      id: "cjvV8Bw",
      key: "quaint-eel-rookie",
      cost: 60,
      name: "Dwarf Lord",
      size: 1,
      defense: 3,
      quality: 3,
      costMode: "manually",
      upgrades: ["e6sFF", "8PTH6", "pSTUL"],
      equipment: [{ label: "Hand Weapon", attacks: 3, specialRules: [] }],
      specialRules: [
        { key: "fearless", name: "Fearless", rating: "" },
        { key: "hero", name: "Hero", rating: "" },
        { key: "slow", name: "Slow", rating: "" },
        { key: "tough", name: "Tough", rating: "3" },
      ],
      splitPageNumber: 1,
    },
    {
      id: "VsBiDBp",
      key: "exact-eel-pal",
      cost: 70,
      name: "Berserker Lord",
      size: 1,
      defense: 4,
      quality: 3,
      costMode: "manually",
      upgrades: [],
      equipment: [
        { label: "2x Berserker Axes", attacks: 3, specialRules: ["AP(1)"] },
      ],
      specialRules: [
        { key: "fearless", name: "Fearless", rating: "" },
        { key: "furious", name: "Furious", rating: "" },
        { key: "hero", name: "Hero", rating: "" },
        { key: "slayer", name: "Slayer", rating: "" },
        { key: "slow", name: "Slow", rating: "" },
        { key: "tough", name: "Tough", rating: "3" },
      ],
      splitPageNumber: 1,
    },
    {
      id: "dR1jGlq",
      key: "magic-eel-sister",
      cost: 45,
      name: "Engineer",
      size: 1,
      defense: 3,
      quality: 3,
      costMode: "manually",
      upgrades: ["e6sFF", "8PTH6", "G1IWc"],
      equipment: [{ label: "Hand Weapon", attacks: 3, specialRules: [] }],
      specialRules: [
        { key: "hero", name: "Hero", rating: "" },
        { key: "slow", name: "Slow", rating: "" },
        { key: "tough", name: "Tough", rating: "3" },
      ],
      splitPageNumber: 1,
    },
    {
      id: "Lp9U7oj",
      key: "eldest-eel-veteran",
      cost: 65,
      name: "Rune Master",
      size: 1,
      defense: 3,
      quality: 3,
      costMode: "manually",
      upgrades: ["e6sFF", "qOUzl"],
      equipment: [{ label: "Hand Weapon", attacks: 3, specialRules: [] }],
      specialRules: [
        { key: "hero", name: "Hero", rating: "" },
        { key: "slow", name: "Slow", rating: "" },
        { key: "tough", name: "Tough", rating: "3" },
        { key: "wizard", name: "Wizard", rating: "1" },
      ],
      splitPageNumber: 1,
    },
    {
      id: "eD6Y9zx",
      key: "objective-eel-veteran",
      cost: 75,
      name: "Warriors",
      size: 10,
      defense: 4,
      quality: 4,
      costMode: "manually",
      upgrades: ["fQKsD", "PaZtM"],
      equipment: [{ label: "Hand Weapons", attacks: 1, specialRules: [] }],
      specialRules: [{ key: "slow", name: "Slow", rating: "" }],
      splitPageNumber: 1,
    },
    {
      id: "c9k8A7A",
      key: "impressed-eel-rookie",
      cost: 135,
      name: "Berserkers",
      size: 10,
      defense: 5,
      quality: 4,
      costMode: "manually",
      upgrades: ["fQKsD"],
      equipment: [
        { label: "2x Berserker Axes", attacks: 1, specialRules: ["AP(1)"] },
      ],
      specialRules: [
        { key: "fearless", name: "Fearless", rating: "" },
        { key: "furious", name: "Furious", rating: "" },
        { key: "slayer", name: "Slayer", rating: "" },
        { key: "slow", name: "Slow", rating: "" },
      ],
      splitPageNumber: 1,
    },
    {
      id: "F216V-z",
      key: "many-eel-pal",
      cost: 150,
      name: "Miners",
      size: 10,
      defense: 4,
      quality: 4,
      costMode: "manually",
      upgrades: ["fQKsD", "Gx-GS"],
      equipment: [
        { label: "Great Weapons", attacks: 1, specialRules: ["AP(2)"] },
      ],
      specialRules: [
        { key: "ambush", name: "Ambush", rating: "" },
        { key: "slow", name: "Slow", rating: "" },
      ],
      splitPageNumber: 1,
    },
    {
      id: "Hi7TGUN",
      key: "equal-eel-sister",
      cost: 140,
      name: "Veterans",
      size: 10,
      defense: 3,
      quality: 3,
      costMode: "manually",
      upgrades: ["fQKsD", "1jVG3"],
      equipment: [{ label: "Hand Weapons", attacks: 1, specialRules: [] }],
      specialRules: [
        { key: "fearless", name: "Fearless", rating: "" },
        { key: "slow", name: "Slow", rating: "" },
      ],
      splitPageNumber: 1,
    },
    {
      id: "tc2FA8S",
      key: "desperate-eel-warrior",
      cost: 200,
      name: "Elites",
      size: 10,
      defense: 3,
      quality: 3,
      costMode: "manually",
      upgrades: ["fQKsD"],
      equipment: [
        { label: "Great Weapons", attacks: 2, specialRules: ["AP(2)"] },
      ],
      specialRules: [
        { key: "fearless", name: "Fearless", rating: "" },
        { key: "slow", name: "Slow", rating: "" },
      ],
      splitPageNumber: 1,
    },
    {
      id: "nFNDQQl",
      key: "powerful-eel-warrior",
      cost: 180,
      name: "Iron Warriors",
      size: 10,
      defense: 2,
      quality: 3,
      costMode: "manually",
      upgrades: ["fQKsD", "1jVG3", "K1MZ1"],
      equipment: [{ label: "Hand Weapons", attacks: 1, specialRules: [] }],
      specialRules: [
        { key: "fearless", name: "Fearless", rating: "" },
        { key: "slow", name: "Slow", rating: "" },
      ],
      splitPageNumber: 1,
    },
    {
      id: "NZEEICn",
      key: "ideal-eel-boy",
      cost: 130,
      name: "Golems",
      size: 3,
      defense: 3,
      quality: 4,
      costMode: "manually",
      upgrades: [],
      equipment: [{ label: "Claws", attacks: 3, specialRules: ["AP(1)"] }],
      specialRules: [
        { key: "slow", name: "Slow", rating: "" },
        { key: "tough", name: "Tough", rating: "3" },
      ],
      splitPageNumber: 1,
    },
    {
      id: "sDAWIVX",
      key: "ready-eel-champion",
      cost: 190,
      name: "Steam-Power Suits",
      size: 3,
      defense: 3,
      quality: 3,
      costMode: "manually",
      upgrades: ["6l-Cz"],
      equipment: [
        { label: "Great Weapons", attacks: 3, specialRules: ["AP(2)"] },
      ],
      specialRules: [
        { key: "fearless", name: "Fearless", rating: "" },
        { key: "slow", name: "Slow", rating: "" },
        { key: "tough", name: "Tough", rating: "3" },
      ],
      splitPageNumber: 1,
    },
    {
      id: "w4Mn-i9",
      key: "famous-eel-sister",
      cost: 50,
      name: "Marksmen",
      size: 5,
      defense: 5,
      quality: 4,
      costMode: "manually",
      upgrades: ["fQKsD", "J7DtE"],
      equipment: [
        { label: "Rifles", range: 24, attacks: 1, specialRules: ["AP(1)"] },
        { label: "Hand Weapons", attacks: 1, specialRules: [] },
      ],
      specialRules: [{ key: "slow", name: "Slow", rating: "" }],
      splitPageNumber: 1,
    },
    {
      id: "OSmqM6r",
      key: "obedient-eel-pal",
      cost: 85,
      name: "Rangers",
      size: 5,
      defense: 5,
      quality: 4,
      costMode: "manually",
      upgrades: ["fQKsD", "-pVid"],
      equipment: [
        {
          label: "Crossbows",
          range: 30,
          attacks: 1,
          specialRules: ["Rending"],
        },
        { label: "Hand Weapons", attacks: 1, specialRules: [] },
      ],
      specialRules: [
        { key: "scout", name: "Scout", rating: "" },
        { key: "slow", name: "Slow", rating: "" },
      ],
      splitPageNumber: 1,
    },
    {
      id: "TjCAUzi",
      key: "solar-eel-boy",
      cost: 100,
      name: "Drake Marksmen",
      size: 5,
      defense: 3,
      quality: 3,
      costMode: "manually",
      upgrades: ["fQKsD", "K1MZ1", "7b-lM"],
      equipment: [
        {
          label: "Fire Rifles",
          range: 18,
          attacks: 1,
          specialRules: ["AP(2)"],
        },
        { label: "Hand Weapons", attacks: 1, specialRules: [] },
      ],
      specialRules: [
        { key: "fearless", name: "Fearless", rating: "" },
        { key: "slow", name: "Slow", rating: "" },
      ],
      splitPageNumber: 1,
    },
    {
      id: "ADSGYne",
      key: "crude-eel-champion",
      cost: 90,
      name: "Beast Riders",
      size: 5,
      defense: 4,
      quality: 4,
      costMode: "manually",
      upgrades: ["fQKsD"],
      equipment: [
        { label: "Hand Weapons", attacks: 1, specialRules: [] },
        { label: "Claws", attacks: 1, specialRules: [] },
      ],
      specialRules: [{ key: "impact", name: "Impact", rating: "1" }],
      splitPageNumber: 1,
    },
    {
      id: "-_6qQPK",
      key: "prominent-eel-veteran",
      cost: 240,
      name: "War-Bear Riders",
      size: 3,
      defense: 3,
      quality: 3,
      costMode: "manually",
      upgrades: ["fQKsD", "n7PsN"],
      equipment: [
        { label: "Hand Weapons", attacks: 1, specialRules: [] },
        { label: "Claws", attacks: 3, specialRules: ["AP(1)"] },
      ],
      specialRules: [
        { key: "fearless", name: "Fearless", rating: "" },
        { key: "impact", name: "Impact", rating: "3" },
        { key: "tough", name: "Tough", rating: "3" },
      ],
      splitPageNumber: 1,
    },
    {
      id: "YdV7YrE",
      key: "technical-eel-brother",
      cost: 180,
      name: "Attack Helicopter",
      size: 1,
      defense: 2,
      quality: 3,
      costMode: "manually",
      upgrades: ["8KoAe"],
      equipment: [
        {
          label: "Flamethrower",
          range: 12,
          attacks: 6,
          specialRules: ["AP(1)"],
        },
      ],
      specialRules: [
        { key: "fast", name: "Fast", rating: "" },
        { key: "fearless", name: "Fearless", rating: "" },
        { key: "flying", name: "Flying", rating: "" },
        { key: "tough", name: "Tough", rating: "6" },
      ],
      splitPageNumber: 1,
    },
    {
      id: "iXKcCI1",
      key: "accepted-eel-brother",
      cost: 220,
      name: "Bomber Helicopter",
      size: 1,
      defense: 2,
      quality: 3,
      costMode: "manually",
      upgrades: [],
      equipment: [
        { label: "Machinegun", range: 24, attacks: 4, specialRules: ["AP(1)"] },
      ],
      specialRules: [
        { key: "bombing run", name: "Bombing Run", rating: "" },
        { key: "fast", name: "Fast", rating: "" },
        { key: "fearless", name: "Fearless", rating: "" },
        { key: "flying", name: "Flying", rating: "" },
        { key: "tough", name: "Tough", rating: "6" },
      ],
      splitPageNumber: 1,
    },
    {
      id: "et8Vefp",
      key: "olympic-eel-brother",
      cost: 320,
      name: "Giant Construct",
      size: 1,
      defense: 2,
      quality: 3,
      costMode: "manually",
      upgrades: ["sGKcM"],
      equipment: [
        { label: "Hand Weapon", attacks: 6, specialRules: ["AP(2)"] },
      ],
      specialRules: [
        { key: "fear", name: "Fear", rating: "" },
        { key: "fearless", name: "Fearless", rating: "" },
        { key: "slow", name: "Slow", rating: "" },
        { key: "tough", name: "Tough", rating: "12" },
      ],
      splitPageNumber: 1,
    },
    {
      id: "HNgG_fw",
      key: "fluffy-eel-sister",
      cost: 65,
      name: "Flame Cannon",
      size: 1,
      defense: 4,
      quality: 4,
      costMode: "manually",
      upgrades: [],
      equipment: [
        {
          label: "Flame Cannon",
          range: 18,
          attacks: 6,
          specialRules: ["AP(2)"],
        },
        { label: "Crew", attacks: 3, specialRules: [] },
      ],
      specialRules: [
        { key: "artillery", name: "Artillery", rating: "" },
        { key: "immobile", name: "Immobile", rating: "" },
        { key: "tough", name: "Tough", rating: "3" },
      ],
      splitPageNumber: 1,
    },
    {
      id: "Aw6OiSu",
      key: "very-eel-veteran",
      cost: 60,
      name: "Bolt Thrower",
      size: 1,
      defense: 4,
      quality: 4,
      costMode: "manually",
      upgrades: [],
      equipment: [
        {
          label: "Bolt Thrower",
          range: 48,
          attacks: 1,
          specialRules: ["AP(2)", "Deadly(3)"],
        },
        { label: "Crew", attacks: 3, specialRules: [] },
      ],
      specialRules: [
        { key: "artillery", name: "Artillery", rating: "" },
        { key: "immobile", name: "Immobile", rating: "" },
        { key: "tough", name: "Tough", rating: "3" },
      ],
      splitPageNumber: 1,
    },
    {
      id: "__3j6Ri",
      key: "flying-eel-boy",
      cost: 75,
      name: "Organ Gun",
      size: 1,
      defense: 4,
      quality: 4,
      costMode: "manually",
      upgrades: [],
      equipment: [
        { label: "Organ Gun", range: 24, attacks: 12, specialRules: [] },
        { label: "Crew", attacks: 3, specialRules: [] },
      ],
      specialRules: [
        { key: "artillery", name: "Artillery", rating: "" },
        { key: "immobile", name: "Immobile", rating: "" },
        { key: "tough", name: "Tough", rating: "3" },
      ],
      splitPageNumber: 1,
    },
    {
      id: "QmtAd0y",
      key: "harsh-eel-sister",
      cost: 95,
      name: "Cannon",
      size: 1,
      defense: 4,
      quality: 4,
      costMode: "manually",
      upgrades: [],
      equipment: [
        {
          label: "Cannon",
          range: 48,
          attacks: 1,
          specialRules: ["AP(4)", "Blast(3)"],
        },
        { label: "Crew", attacks: 3, specialRules: [] },
      ],
      specialRules: [
        { key: "artillery", name: "Artillery", rating: "" },
        { key: "immobile", name: "Immobile", rating: "" },
        { key: "tough", name: "Tough", rating: "3" },
      ],
      splitPageNumber: 1,
    },
    {
      id: "AW-dKPE",
      key: "youthful-eel-brother",
      cost: 130,
      name: "Stone Thrower",
      size: 1,
      defense: 4,
      quality: 4,
      costMode: "manually",
      upgrades: [],
      equipment: [
        {
          label: "Stone Thrower",
          range: 48,
          attacks: 1,
          specialRules: ["AP(2)", "Blast(6)", "Indirect"],
        },
        { label: "Crew", attacks: 3, specialRules: [] },
      ],
      specialRules: [
        { key: "artillery", name: "Artillery", rating: "" },
        { key: "immobile", name: "Immobile", rating: "" },
        { key: "tough", name: "Tough", rating: "3" },
      ],
      splitPageNumber: 1,
    },
  ],
  upgradePackages: [
    {
      uid: "e6sFF",
      hint: "A - Heroes Melee",
      sections: [
        {
          label: "Replace Hand Weapon",
          options: [
            {
              cost: 5,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "2x Hand Weapons",
                  type: "ArmyBookWeapon",
                  label: "2x Hand Weapons (A3)",
                  range: 0,
                  attacks: 3,
                  condition: "",
                  specialRules: [],
                },
              ],
              label: "2x Hand Weapons (A3)",
            },
            {
              cost: 5,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Halberd",
                  type: "ArmyBookWeapon",
                  label: "Halberd (A3, Rending)",
                  range: 0,
                  attacks: 3,
                  condition: "",
                  specialRules: [
                    {
                      key: "rending",
                      name: "Rending",
                      type: "ArmyBookRule",
                      label: "Rending",
                      modify: false,
                      rating: "",
                      condition: "",
                    },
                  ],
                },
              ],
              label: "Halberd (A3, Rending)",
            },
            {
              cost: 5,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Great Weapon",
                  type: "ArmyBookWeapon",
                  label: "Great Weapon (A3, AP(2))",
                  range: 0,
                  attacks: 3,
                  condition: "",
                  specialRules: [
                    {
                      key: "ap",
                      name: "AP",
                      type: "ArmyBookRule",
                      label: "AP(2)",
                      modify: false,
                      rating: "2",
                      condition: "",
                    },
                  ],
                },
              ],
              label: "Great Weapon (A3, AP(2))",
            },
            {
              cost: 5,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Spear",
                  type: "ArmyBookWeapon",
                  label: "Spear (A3, Phalanx)",
                  range: 0,
                  attacks: 3,
                  condition: "",
                  specialRules: [
                    {
                      key: "phalanx",
                      name: "Phalanx",
                      type: "ArmyBookRule",
                      label: "Phalanx",
                      modify: false,
                      rating: "",
                      condition: "",
                    },
                  ],
                },
              ],
              label: "Spear (A3, Phalanx)",
            },
          ],
        },
      ],
    },
    {
      uid: "8PTH6",
      hint: "B - Heroes Ranged",
      sections: [
        {
          label: "Upgrade with one",
          options: [
            {
              cost: 5,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Pistol",
                  type: "ArmyBookWeapon",
                  label: 'Pistol (12", A1, AP(1))',
                  range: 12,
                  attacks: 1,
                  condition: "",
                  specialRules: [
                    {
                      key: "ap",
                      name: "AP",
                      type: "ArmyBookRule",
                      label: "AP(1)",
                      modify: false,
                      rating: "1",
                      condition: "",
                    },
                  ],
                },
              ],
              label: 'Pistol (12", A1, AP(1))',
            },
            {
              cost: 10,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "2x Pistols",
                  type: "ArmyBookWeapon",
                  label: '2x Pistols (12", A1, AP(1))',
                  range: 12,
                  attacks: 1,
                  condition: "",
                  specialRules: [
                    {
                      key: "ap",
                      name: "AP",
                      type: "ArmyBookRule",
                      label: "AP(1)",
                      modify: false,
                      rating: "1",
                      condition: "",
                    },
                  ],
                },
              ],
              label: '2x Pistols (12", A1, AP(1))',
            },
            {
              cost: 10,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Rifle",
                  type: "ArmyBookWeapon",
                  label: 'Rifle (24", A1, AP(1))',
                  range: 24,
                  attacks: 1,
                  condition: "",
                  specialRules: [
                    {
                      key: "ap",
                      name: "AP",
                      type: "ArmyBookRule",
                      label: "AP(1)",
                      modify: false,
                      rating: "1",
                      condition: "",
                    },
                  ],
                },
              ],
              label: 'Rifle (24", A1, AP(1))',
            },
            {
              cost: 15,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Crossbow",
                  type: "ArmyBookWeapon",
                  label: 'Crossbow (30", A1, Rending)',
                  range: 30,
                  attacks: 1,
                  condition: "",
                  specialRules: [
                    {
                      key: "rending",
                      name: "Rending",
                      type: "ArmyBookRule",
                      label: "Rending",
                      modify: false,
                      rating: "",
                      condition: "",
                    },
                  ],
                },
              ],
              label: 'Crossbow (30", A1, Rending)',
            },
          ],
        },
      ],
    },
    {
      uid: "pSTUL",
      hint: "C - Lord",
      sections: [
        {
          label: "Upgrade with",
          options: [
            {
              cost: "30",
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  key: "grudge",
                  name: "Grudge",
                  type: "ArmyBookRule",
                  label: "Grudge",
                  modify: false,
                  rating: "",
                  condition: "",
                },
              ],
              label: "Grudge",
            },
          ],
        },
        {
          label: "Mount on",
          options: [
            {
              cost: "15",
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Beast",
                  type: "ArmyBookItem",
                  label: "Beast - Claws (A1), Impact(1), Swift",
                  content: [
                    {
                      name: "Claws",
                      type: "ArmyBookWeapon",
                      label: "Claws (A1)",
                      range: 0,
                      attacks: 1,
                      condition: "",
                      specialRules: [],
                    },
                    {
                      key: "impact",
                      name: "Impact",
                      type: "ArmyBookRule",
                      label: "Impact(1)",
                      modify: false,
                      rating: "1",
                      condition: "",
                    },
                    {
                      key: "swift",
                      name: "Swift",
                      type: "ArmyBookRule",
                      label: "Swift",
                      modify: false,
                      rating: "",
                      condition: "",
                    },
                  ],
                },
              ],
              label: "Beast - Claws (A1), Impact(1), Swift",
            },
            {
              cost: "70",
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Ancestral Stone",
                  type: "ArmyBookItem",
                  label: "Ancestral Stone - Tough(+3)",
                  content: [
                    {
                      key: "tough",
                      name: "Tough",
                      type: "ArmyBookRule",
                      label: "Tough(+3)",
                      modify: true,
                      rating: "3",
                      condition: "",
                    },
                  ],
                },
              ],
              label: "Ancestral Stone - Tough(+3)",
            },
            {
              cost: "80",
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Shield Carriers",
                  type: "ArmyBookItem",
                  label: "Shield Carriers - Hand Weapons (A4), Tough(+3)",
                  content: [
                    {
                      name: "Hand Weapons",
                      type: "ArmyBookWeapon",
                      label: "Hand Weapons (A4)",
                      range: 0,
                      attacks: 4,
                      condition: "",
                      specialRules: [],
                    },
                    {
                      key: "tough",
                      name: "Tough",
                      type: "ArmyBookRule",
                      label: "Tough(+3)",
                      modify: true,
                      rating: "3",
                      condition: "",
                    },
                  ],
                },
              ],
              label: "Shield Carriers - Hand Weapons (A4), Tough(+3)",
            },
            {
              cost: "120",
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Great War-Bear",
                  type: "ArmyBookItem",
                  label:
                    "Great War-Bear - Claws (A3, AP(1)), Fear, Impact(3), Swift, Tough(+3)",
                  content: [
                    {
                      name: "Claws",
                      type: "ArmyBookWeapon",
                      label: "Claws (A3, AP(1))",
                      range: 0,
                      attacks: 3,
                      condition: "",
                      specialRules: [
                        {
                          key: "ap",
                          name: "AP",
                          type: "ArmyBookRule",
                          label: "AP(1)",
                          modify: false,
                          rating: "1",
                          condition: "",
                        },
                      ],
                    },
                    {
                      key: "fear",
                      name: "Fear",
                      type: "ArmyBookRule",
                      label: "Fear",
                      modify: false,
                      rating: "",
                      condition: "",
                    },
                    {
                      key: "impact",
                      name: "Impact",
                      type: "ArmyBookRule",
                      label: "Impact(3)",
                      modify: false,
                      rating: "3",
                      condition: "",
                    },
                    {
                      key: "swift",
                      name: "Swift",
                      type: "ArmyBookRule",
                      label: "Swift",
                      modify: false,
                      rating: "",
                      condition: "",
                    },
                    {
                      key: "tough",
                      name: "Tough",
                      type: "ArmyBookRule",
                      label: "Tough(+3)",
                      modify: true,
                      rating: "3",
                      condition: "",
                    },
                  ],
                },
              ],
              label:
                "Great War-Bear - Claws (A3, AP(1)), Fear, Impact(3), Swift, Tough(+3)",
            },
          ],
        },
      ],
    },
    {
      uid: "G1IWc",
      hint: "D - Engineer",
      sections: [
        {
          label: "Upgrade with",
          options: [
            {
              cost: 45,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  key: "ballistic master",
                  name: "Ballistic Master",
                  type: "ArmyBookRule",
                  label: "Ballistic Master",
                  modify: false,
                  rating: "",
                  condition: "",
                },
              ],
              label: "Ballistic Master",
            },
          ],
        },
        {
          label: "Upgrade with one",
          options: [
            {
              cost: 20,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Flame-Rifle",
                  type: "ArmyBookWeapon",
                  label: 'Flame-Rifle (12", A6, AP(1))',
                  range: 12,
                  attacks: 6,
                  condition: "",
                  specialRules: [
                    {
                      key: "ap",
                      name: "AP",
                      type: "ArmyBookRule",
                      label: "AP(1)",
                      modify: false,
                      rating: "1",
                      condition: "",
                    },
                  ],
                },
              ],
              label: 'Flame-Rifle (12", A6, AP(1))',
            },
            {
              cost: 25,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Organ-Rifle",
                  type: "ArmyBookWeapon",
                  label: 'Organ-Rifle (12", A12)',
                  range: 12,
                  attacks: 12,
                  condition: "",
                  specialRules: [],
                },
              ],
              label: 'Organ-Rifle (12", A12)',
            },
          ],
        },
      ],
    },
    {
      uid: "qOUzl",
      hint: "E - Rune Master",
      sections: [
        {
          label: "Upgrade Wizard(1)",
          options: [
            {
              cost: 15,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  key: "wizard",
                  name: "Wizard",
                  type: "ArmyBookRule",
                  label: "Wizard(2)",
                  modify: false,
                  rating: "2",
                  condition: "",
                },
              ],
              label: "Wizard(2)",
            },
          ],
        },
      ],
    },
    {
      uid: "fQKsD",
      hint: "F - Command Group",
      sections: [
        {
          label: "Upgrade with",
          options: [
            {
              cost: 5,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  key: "sergeant",
                  name: "Sergeant",
                  type: "ArmyBookRule",
                  label: "Sergeant",
                  modify: false,
                  rating: "",
                  condition: "",
                },
              ],
              label: "Sergeant",
            },
            {
              cost: 10,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  key: "musician",
                  name: "Musician",
                  type: "ArmyBookRule",
                  label: "Musician",
                  modify: false,
                  rating: "",
                  condition: "",
                },
              ],
              label: "Musician",
            },
            {
              cost: 10,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  key: "standard bearer",
                  name: "Standard Bearer",
                  type: "ArmyBookRule",
                  label: "Standard Bearer",
                  modify: false,
                  rating: "",
                  condition: "",
                },
              ],
              label: "Standard Bearer",
            },
          ],
        },
      ],
    },
    {
      uid: "PaZtM",
      hint: "G - Warriors",
      sections: [
        {
          label: "Replace all Hand Weapons",
          options: [
            {
              cost: 10,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Halberds",
                  type: "ArmyBookWeapon",
                  label: "Halberds (A1, Rending)",
                  range: 0,
                  attacks: 1,
                  condition: "",
                  specialRules: [
                    {
                      key: "rending",
                      name: "Rending",
                      type: "ArmyBookRule",
                      label: "Rending",
                      modify: false,
                      rating: "",
                      condition: "",
                    },
                  ],
                },
              ],
              label: "Halberds (A1, Rending)",
            },
            {
              cost: 15,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "2x Hand Weapons",
                  type: "ArmyBookWeapon",
                  label: "2x Hand Weapons (A1)",
                  range: 0,
                  attacks: 1,
                  condition: "",
                  specialRules: [],
                },
              ],
              label: "2x Hand Weapons (A1)",
            },
            {
              cost: 15,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Great Weapons",
                  type: "ArmyBookWeapon",
                  label: "Great Weapons (A1, AP(2))",
                  range: 0,
                  attacks: 1,
                  condition: "",
                  specialRules: [
                    {
                      key: "ap",
                      name: "AP",
                      type: "ArmyBookRule",
                      label: "AP(2)",
                      modify: false,
                      rating: "2",
                      condition: "",
                    },
                  ],
                },
              ],
              label: "Great Weapons (A1, AP(2))",
            },
            {
              cost: 30,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Spears",
                  type: "ArmyBookWeapon",
                  label: "Spears (A1, Phalanx)",
                  range: 0,
                  attacks: 1,
                  condition: "",
                  specialRules: [
                    {
                      key: "phalanx",
                      name: "Phalanx",
                      type: "ArmyBookRule",
                      label: "Phalanx",
                      modify: false,
                      rating: "",
                      condition: "",
                    },
                  ],
                },
              ],
              label: "Spears (A1, Phalanx)",
            },
          ],
        },
      ],
    },
    {
      uid: "Gx-GS",
      hint: "H - Miners",
      sections: [
        {
          label: "Upgrade any model with",
          options: [
            {
              cost: 5,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Shrapnel Bombs",
                  type: "ArmyBookWeapon",
                  label: 'Shrapnel Bombs (6", A1, AP(1), Blast(3))',
                  range: 6,
                  attacks: 1,
                  condition: "",
                  specialRules: [
                    {
                      key: "ap",
                      name: "AP",
                      type: "ArmyBookRule",
                      label: "AP(1)",
                      modify: false,
                      rating: "1",
                      condition: "",
                    },
                    {
                      key: "blast",
                      name: "Blast",
                      type: "ArmyBookRule",
                      label: "Blast(3)",
                      modify: false,
                      rating: "3",
                      condition: "",
                    },
                  ],
                },
              ],
              label: 'Shrapnel Bombs (6", A1, AP(1), Blast(3))',
            },
          ],
        },
        {
          label: "Replace one Great Weapon",
          options: [
            {
              cost: 30,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Mining Drill",
                  type: "ArmyBookWeapon",
                  label: "Mining Drill (A1, AP(3), Drill)",
                  range: 0,
                  attacks: 1,
                  condition: "",
                  specialRules: [
                    {
                      key: "ap",
                      name: "AP",
                      type: "ArmyBookRule",
                      label: "AP(3)",
                      modify: false,
                      rating: "3",
                      condition: "",
                    },
                    {
                      key: "drill",
                      name: "Drill",
                      type: "ArmyBookRule",
                      label: "Drill",
                      modify: false,
                      rating: "",
                      condition: "",
                    },
                  ],
                },
              ],
              label: "Mining Drill (A1, AP(3), Drill)",
            },
          ],
        },
      ],
    },
    {
      uid: "1jVG3",
      hint: "I - Veterans",
      sections: [
        {
          label: "Replace all Hand Weapons",
          options: [
            {
              cost: 10,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Halbers",
                  type: "ArmyBookWeapon",
                  label: "Halbers (A1, Rending)",
                  range: 0,
                  attacks: 1,
                  condition: "",
                  specialRules: [
                    {
                      key: "rending",
                      name: "Rending",
                      type: "ArmyBookRule",
                      label: "Rending",
                      modify: false,
                      rating: "",
                      condition: "",
                    },
                  ],
                },
              ],
              label: "Halbers (A1, Rending)",
            },
            {
              cost: 20,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "2x Hand Weapons",
                  type: "ArmyBookWeapon",
                  label: "2x Hand Weapons (A1)",
                  range: 0,
                  attacks: 1,
                  condition: "",
                  specialRules: [],
                },
              ],
              label: "2x Hand Weapons (A1)",
            },
            {
              cost: 20,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Great Weapons",
                  type: "ArmyBookWeapon",
                  label: "Great Weapons (A1, AP(2))",
                  range: 0,
                  attacks: 1,
                  condition: "",
                  specialRules: [
                    {
                      key: "ap",
                      name: "AP",
                      type: "ArmyBookRule",
                      label: "AP(2)",
                      modify: false,
                      rating: "2",
                      condition: "",
                    },
                  ],
                },
              ],
              label: "Great Weapons (A1, AP(2))",
            },
            {
              cost: 30,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Spears",
                  type: "ArmyBookWeapon",
                  label: "Spears (A1, Phalanx)",
                  range: 0,
                  attacks: 1,
                  condition: "",
                  specialRules: [
                    {
                      key: "phalanx",
                      name: "Phalanx",
                      type: "ArmyBookRule",
                      label: "Phalanx",
                      modify: false,
                      rating: "",
                      condition: "",
                    },
                  ],
                },
              ],
              label: "Spears (A1, Phalanx)",
            },
          ],
        },
      ],
    },
    {
      uid: "K1MZ1",
      hint: "J - Iron Warriors",
      sections: [
        {
          label: "Upgrade one model with any",
          options: [
            {
              cost: 5,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Shrapnel Bombs",
                  type: "ArmyBookWeapon",
                  label: 'Shrapnel Bombs (6", A1, AP(1), Blast(3))',
                  range: 6,
                  attacks: 1,
                  condition: "",
                  specialRules: [
                    {
                      key: "ap",
                      name: "AP",
                      type: "ArmyBookRule",
                      label: "AP(1)",
                      modify: false,
                      rating: "1",
                      condition: "",
                    },
                    {
                      key: "blast",
                      name: "Blast",
                      type: "ArmyBookRule",
                      label: "Blast(3)",
                      modify: false,
                      rating: "3",
                      condition: "",
                    },
                  ],
                },
              ],
              label: 'Shrapnel Bombs (6", A1, AP(1), Blast(3))',
            },
            {
              cost: 10,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "2x Fire Pistols",
                  type: "ArmyBookWeapon",
                  label: '2x Fire Pistols (12", A1, AP(2))',
                  range: 12,
                  attacks: 1,
                  condition: "",
                  specialRules: [
                    {
                      key: "ap",
                      name: "AP",
                      type: "ArmyBookRule",
                      label: "AP(2)",
                      modify: false,
                      rating: "2",
                      condition: "",
                    },
                  ],
                },
              ],
              label: '2x Fire Pistols (12", A1, AP(2))',
            },
          ],
        },
      ],
    },
    {
      uid: "6l-Cz",
      hint: "K - Suits",
      sections: [
        {
          label: "Upgrade any model with",
          options: [
            {
              cost: 5,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Steam-Gun",
                  type: "ArmyBookWeapon",
                  label: 'Steam-Gun (24", A1, AP(1))',
                  range: 24,
                  attacks: 1,
                  condition: "",
                  specialRules: [
                    {
                      key: "ap",
                      name: "AP",
                      type: "ArmyBookRule",
                      label: "AP(1)",
                      modify: false,
                      rating: "1",
                      condition: "",
                    },
                  ],
                },
              ],
              label: 'Steam-Gun (24", A1, AP(1))',
            },
          ],
        },
      ],
    },
    {
      uid: "J7DtE",
      hint: "L - Marksmen",
      sections: [
        {
          label: "Replace all Rifles",
          options: [
            {
              cost: 5,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Crossbows",
                  type: "ArmyBookWeapon",
                  label: "Crossbows (A1, Rending)",
                  range: 0,
                  attacks: 1,
                  condition: "",
                  specialRules: [
                    {
                      key: "rending",
                      name: "Rending",
                      type: "ArmyBookRule",
                      label: "Rending",
                      modify: false,
                      rating: "",
                      condition: "",
                    },
                  ],
                },
              ],
              label: "Crossbows (A1, Rending)",
            },
          ],
        },
        {
          label: "Replace one Rifle",
          options: [
            {
              cost: 0,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "2x Pistols",
                  type: "ArmyBookWeapon",
                  label: '2x Pistols (12", A1, AP(1))',
                  range: 12,
                  attacks: 1,
                  condition: "",
                  specialRules: [
                    {
                      key: "ap",
                      name: "AP",
                      type: "ArmyBookRule",
                      label: "AP(1)",
                      modify: false,
                      rating: "1",
                      condition: "",
                    },
                  ],
                },
              ],
              label: '2x Pistols (12", A1, AP(1))',
            },
          ],
        },
      ],
    },
    {
      uid: "-pVid",
      hint: "M - Rangers",
      sections: [
        {
          label: "Upgrade all models with",
          options: [
            {
              cost: 10,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Throwing Axes",
                  type: "ArmyBookWeapon",
                  label: 'Throwing Axes (12", A1, AP(1))',
                  range: 12,
                  attacks: 1,
                  condition: "",
                  specialRules: [
                    {
                      key: "ap",
                      name: "AP",
                      type: "ArmyBookRule",
                      label: "AP(1)",
                      modify: false,
                      rating: "1",
                      condition: "",
                    },
                  ],
                },
              ],
              label: 'Throwing Axes (12", A1, AP(1))',
            },
          ],
        },
      ],
    },
    {
      uid: "7b-lM",
      hint: "N - Drakes",
      sections: [
        {
          label: "Upgrade one model with",
          options: [
            {
              cost: 5,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Shrapnel Bombs",
                  type: "ArmyBookWeapon",
                  label: 'Shrapnel Bombs (6", A1, AP(1), Blast(3))',
                  range: 6,
                  attacks: 1,
                  condition: "",
                  specialRules: [
                    {
                      key: "ap",
                      name: "AP",
                      type: "ArmyBookRule",
                      label: "AP(1)",
                      modify: false,
                      rating: "1",
                      condition: "",
                    },
                    {
                      key: "blast",
                      name: "Blast",
                      type: "ArmyBookRule",
                      label: "Blast(3)",
                      modify: false,
                      rating: "3",
                      condition: "",
                    },
                  ],
                },
              ],
              label: 'Shrapnel Bombs (6", A1, AP(1), Blast(3))',
            },
          ],
        },
        {
          label: "Replace one Fire Rifle",
          options: [
            {
              cost: 5,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "2x Fire Pistols",
                  type: "ArmyBookWeapon",
                  label: '2x Fire Pistols (12", A1, AP(2))',
                  range: 12,
                  attacks: 1,
                  condition: "",
                  specialRules: [
                    {
                      key: "ap",
                      name: "AP",
                      type: "ArmyBookRule",
                      label: "AP(2)",
                      modify: false,
                      rating: "2",
                      condition: "",
                    },
                  ],
                },
              ],
              label: '2x Fire Pistols (12", A1, AP(2))',
            },
            {
              cost: 15,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Torpedo Rifle",
                  type: "ArmyBookWeapon",
                  label: 'Torpedo Rifle (24", A1, AP(3), Deadly(3))',
                  range: 24,
                  attacks: 1,
                  condition: "",
                  specialRules: [
                    {
                      key: "ap",
                      name: "AP",
                      type: "ArmyBookRule",
                      label: "AP(3)",
                      modify: false,
                      rating: "3",
                      condition: "",
                    },
                    {
                      key: "deadly",
                      name: "Deadly",
                      type: "ArmyBookRule",
                      label: "Deadly(3)",
                      modify: false,
                      rating: "3",
                      condition: "",
                    },
                  ],
                },
              ],
              label: 'Torpedo Rifle (24", A1, AP(3), Deadly(3))',
            },
          ],
        },
      ],
    },
    {
      uid: "n7PsN",
      hint: " O - War-Bears",
      sections: [
        {
          label: "Replace all Hand Weapons",
          options: [
            {
              cost: 10,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Axe-Halberds",
                  type: "ArmyBookWeapon",
                  label: "Axe-Halberds (A1, AP(1), Rending)",
                  range: 0,
                  attacks: 1,
                  condition: "",
                  specialRules: [
                    {
                      key: "ap",
                      name: "AP",
                      type: "ArmyBookRule",
                      label: "AP(1)",
                      modify: false,
                      rating: "1",
                      condition: "",
                    },
                    {
                      key: "rending",
                      name: "Rending",
                      type: "ArmyBookRule",
                      label: "Rending",
                      modify: false,
                      rating: "",
                      condition: "",
                    },
                  ],
                },
              ],
              label: "Axe-Halberds (A1, AP(1), Rending)",
            },
          ],
        },
      ],
    },
    {
      uid: "8KoAe",
      hint: "P - Attack Helicopter",
      sections: [
        {
          label: "Upgrade with any",
          options: [
            {
              cost: 10,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  key: "scout",
                  name: "Scout",
                  type: "ArmyBookRule",
                  label: "Scout",
                  modify: false,
                  rating: "",
                  condition: "",
                },
              ],
              label: "Scout",
            },
            {
              cost: 15,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  key: "attack bomb",
                  name: "Attack Bomb",
                  type: "ArmyBookRule",
                  label: "Attack Bomb",
                  modify: false,
                  rating: "",
                  condition: "",
                },
              ],
              label: "Attack Bomb",
            },
          ],
        },
        {
          label: "Replace Flamethrower",
          options: [
            {
              cost: 0,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Fire Machinegun",
                  type: "ArmyBookWeapon",
                  label: 'Fire Machinegun (18", A3, AP(2))',
                  range: 18,
                  attacks: 3,
                  condition: "",
                  specialRules: [
                    {
                      key: "ap",
                      name: "AP",
                      type: "ArmyBookRule",
                      label: "AP(2)",
                      modify: false,
                      rating: "2",
                      condition: "",
                    },
                  ],
                },
              ],
              label: 'Fire Machinegun (18", A3, AP(2))',
            },
          ],
        },
      ],
    },
    {
      uid: "sGKcM",
      hint: "Q - Giant Construct",
      sections: [
        {
          label: "Replace Hand Weapon",
          options: [
            {
              cost: 10,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Great Weapon",
                  type: "ArmyBookWeapon",
                  label: "Great Weapon (A4, AP(4))",
                  range: 0,
                  attacks: 4,
                  condition: "",
                  specialRules: [
                    {
                      key: "ap",
                      name: "AP",
                      type: "ArmyBookRule",
                      label: "AP(4)",
                      modify: false,
                      rating: "4",
                      condition: "",
                    },
                  ],
                },
              ],
              label: "Great Weapon (A4, AP(4))",
            },
          ],
        },
        {
          label: "Upgrade with up to two",
          options: [
            {
              cost: 25,
              type: "ArmyBookUpgradeOption",
              gains: [
                {
                  name: "Heavy Steam-Gun",
                  type: "ArmyBookWeapon",
                  label: 'Heavy Steam-Gun (24", A1, AP(2), Blast(3))',
                  range: 24,
                  attacks: 1,
                  condition: "",
                  specialRules: [
                    {
                      key: "ap",
                      name: "AP",
                      type: "ArmyBookRule",
                      label: "AP(2)",
                      modify: false,
                      rating: "2",
                      condition: "",
                    },
                    {
                      key: "blast",
                      name: "Blast",
                      type: "ArmyBookRule",
                      label: "Blast(3)",
                      modify: false,
                      rating: "3",
                      condition: "",
                    },
                  ],
                },
              ],
              label: 'Heavy Steam-Gun (24", A1, AP(2), Blast(3))',
            },
          ],
        },
      ],
    },
  ],
  specialRules: [
    {
      id: "zhURU",
      key: "attack-bomb",
      hint: "Whenever this unit moves over enemies pick one of them and roll 1 die, on a 2+ it takes 3 hits with AP(1).",
      name: "Attack Bomb",
      tags: [],
      label: "Attack Bomb",
      forUnit: true,
      forWeapon: false,
      hasRating: false,
      description:
        "Whenever this unit moves over enemies pick one of them and roll 1 die, on a 2+ it takes 3 hits with AP(1).",
    },
    {
      id: "ip8uK",
      key: "ballistic-master",
      hint: "When the hero is activated pick one friendly Artillery unit within 6”, which may either get +2 to its shooting rolls or move up to 6” during its next activation.",
      name: "Ballistic Master",
      tags: [],
      label: "Ballistic Master",
      forUnit: true,
      forWeapon: false,
      hasRating: false,
      description:
        "When the hero is activated pick one friendly Artillery unit within 6”, which may either get +2 to its shooting rolls or move up to 6” during its next activation.",
    },
    {
      id: "NXTYS",
      key: "bombing-run",
      hint: "Whenever this unit moves over enemies pick one of them and roll 3 dice, for each 2+ it takes 3 hits with AP(1).",
      name: "Bombing Run",
      tags: [],
      label: "Bombing Run",
      forUnit: true,
      forWeapon: false,
      hasRating: false,
      description:
        "Whenever this unit moves over enemies pick one of them and roll 3 dice, for each 2+ it takes 3 hits with AP(1).",
    },
    {
      id: "TJnGU",
      key: "drill",
      hint: "The unit may be deployed from Ambush at up to 3” from enemy units.",
      name: "Drill",
      tags: [],
      label: "Drill",
      forUnit: false,
      forWeapon: true,
      hasRating: false,
      description:
        "The unit may be deployed from Ambush at up to 3” from enemy units.",
    },
    {
      id: "5KK6z",
      key: "grudge",
      hint: "The hero and his unit get +1 to their rolls when fighting in melee.",
      name: "Grudge",
      tags: [],
      label: "Grudge",
      forUnit: true,
      forWeapon: false,
      hasRating: false,
      description:
        "The hero and his unit get +1 to their rolls when fighting in melee.",
    },
    {
      id: "CGyFU",
      key: "slayer",
      hint: "This model gets AP(+2) when fighting units with Tough(3) or higher.",
      name: "Slayer",
      tags: [],
      label: "Slayer",
      forUnit: true,
      forWeapon: false,
      hasRating: false,
      description:
        "This model gets AP(+2) when fighting units with Tough(3) or higher.",
    },
    {
      id: "ttoVs",
      key: "swift",
      hint: "The hero may ignore the Slow rule.",
      name: "Swift",
      tags: [],
      label: "Swift",
      forUnit: true,
      forWeapon: false,
      hasRating: false,
      description: "The hero may ignore the Slow rule.",
    },
  ],
  spells: [
    {
      id: "8Df6t",
      name: "Spite Rune",
      effect:
        "Target enemy unit within 12” gets -1 to hit in melee next time it fights.",
      threshold: 4,
    },
    {
      id: "0qTqP",
      name: "Smiting Rune",
      effect: "Target enemy unit within 12” takes 4 automatic hits.",
      threshold: 4,
    },
    {
      id: "aY5yj",
      name: "Battle Rune",
      effect: "Target friendly unit within 12” gets +6” next time it moves.",
      threshold: 5,
    },
    {
      id: "5okj2",
      name: "Breaking Rune",
      effect:
        "Target enemy model within 12” takes 2 automatic hits with AP(2).",
      threshold: 5,
    },
    {
      id: "MsLeZ",
      name: "Drill Rune",
      effect:
        "Target piece of terrain within 6” may be moved by up to 6” in any direction or may be removed from play.",
      threshold: 6,
    },
    {
      id: "A3zf6",
      name: "Cleaving Rune",
      effect: "Target 2 enemy units within 12” take 6 automatic hits each.",
      threshold: 6,
    },
  ],
  modifiedAt: "2021-09-20T16:36:01.610Z",
  official: false,
  public: true,
  versionString: "draft",
  coverImagePath: null,
  coverImageCredit: null,
  username: "Darguth",
  gameSystemSlug: "age-of-fantasy",
  fullname: "Age of Fantasy",
  aberration: "AOF",
  universe: "Age of Fantasy",
  shortname: "Age of Fantasy",
};

const result = {
  ...input,
  units: input.units.map((u) => ({
    name: u.name,
    cost: u.cost,
    size: u.size,
    quality: u.quality + "+",
    defense: u.defense + "+",
    equipment: u.equipment.map((e) => ({
      ...e,
      name: e.label,
    })),
    specialRules: u.specialRules.map(r => r.name + (r.rating ? `(${r.rating})` : ''))
  })),
  upgradeSets: input.upgradePackages.map(set => ({
      id: set.uid,
      upgrades: set.sections.map(u => ({
          text: u.label,
          
      }))
  }))
};

console.log(result);
